// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type SpacetravelingDocumentDataSlicesSlice = never

/**
 * Content for spaceTraveling documents
 */
interface SpacetravelingDocumentData {
  /**
   * Slice Zone field in *spaceTraveling*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: spacetraveling.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SpacetravelingDocumentDataSlicesSlice> /**
   * Meta Description field in *spaceTraveling*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: spacetraveling.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *spaceTraveling*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: spacetraveling.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *spaceTraveling*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: spacetraveling.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * spaceTraveling document from Prismic
 *
 * - **API ID**: `spacetraveling`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpacetravelingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SpacetravelingDocumentData>,
    'spacetraveling',
    Lang
  >

export type AllDocumentTypes = SpacetravelingDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      SpacetravelingDocument,
      SpacetravelingDocumentData,
      SpacetravelingDocumentDataSlicesSlice,
      AllDocumentTypes,
    }
  }
}
